### PR TITLE
bump 11.1.1

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by carlodri** [comment]
I'm stuck diagnosing this....if anyone can help...

**Comment by jakirkham** [comment]
Thanks Carlo! 🙏

Have jumped ahead to 11.9.0 in PR ( https://github.com/conda-forge/qpdf-feedstock/pull/39 ), which seems to be working

Not sure if 11.1.1 or earlier versions are needed. If not, maybe we can go ahead with that one

Please let me know what you think 🙂

**Comment by carlodri** [comment]
superseded by #38

**Pull request closed without merging**
